# https://github.com/Huachao/vscode-restclient

################################################################################

# Variables

@url=http://localhost:9740

################################################################################

GET {{url}}/healthz
Content-Type: application/json

################################################################################
